### ISSUE TITLE
Fix the license 

### ISSUE THREAD

**Issue by MrCeleryman** [JumboInteractiveLimited/redux-cache#1]
Please change to GPLv3 its the future of open source

**Comment by patrickgordon** [comment]
Can you briefly detail the differences/advantages over MIT?

**Comment by MrCeleryman** [comment]
I will let the prophet himself explain it [here](https://www.youtube.com/watch?v=E5G7FU5j2Uc "GPLv3 is for big boys")

[![GPLv3 is for big boys](https://img.youtube.com/vi/E5G7FU5j2Uc/0.jpg)](https://www.youtube.com/watch?v=E5G7FU5j2Uc "GPLv3 is for big boys")

**Comment by patrickgordon** [comment]
Leaving as MIT for now.
