### ISSUE TITLE
Where is the cache stored?

### ISSUE THREAD

**Issue by darewreck54** [JumboInteractiveLimited/redux-cache#10]
This isn't really an issue, but more of a question.

Is the cache stored in the redux store?  Or is it copied to local storage for example?   Also if it's stored in the redux store, doesn't it just get erased during a refresh?

Thanks,
Derek

**Comment by patrickgordon** [comment]
Hi Derek,

The cache is essentially just comprised of two things: 
1 - your data that is already in your reducer; and
2 - a TTL value which is stored in your reducer 

Redux cache will just check if the TTL value is still valid and if so won’t fetch new data. The data already in your store should then be used.

As to persistence, that’s not the concern of this library and there are great libraries, such as redux-persist, which already do this. This is to ensure that redux-cache is kept as lean in code size and to a single purpose as possible.

For what it’s worth, I use redux-cache with redux-persist together in almost every project.

Hope this helps

Cheers
Patrick.
