### ISSUE TITLE
Invalidate cache requires an accessStrategy option

### ISSUE THREAD

**Issue by patrickgordon** [JumboInteractiveLimited/redux-cache#3]
By introducing the ability to apply a cache value on a deeply nested object (by using `accessStrategy`), there is a need to be able to also target the invalidate cache `accessStrategy`. 

It currently assumes it would be on the top level which it may not be.

**Comment by irtiza-rizvi** [comment]
Second this.  There's no clean way to invalidate the cache if you check if the cache is valid via an access strategy.

**Comment by patrickgordon** [comment]
@irtiza-rizvi what I think we would need is a similar `accessStrategy` as a param for the `invalidateCache` action.

This then needs to be looked for in the `cacheEnhancer` to determine how to invalidate for a given reducer.

**Comment by irtiza-rizvi** [comment]
@patrickgordon that could work.  You would probably put the `accessStrategy` in the payload of the `INVALIDATE_CACHE` action and use that when you `updateState` in the `cacheEnhancer`.  Another "quick" fix would be to have the `accessStrategy` as a config item in `cacheEnhancer` and use that throughout the package.  You lose the flexibility of having different access strategies for different actions this way, but it would be simpler to implement I feel.

Ultimately though, I think having an `accessStrategy` is overkill because the redux store is almost always just a nested object.  I think instead of using an `accessStrategy`, you could do the following:

1. Update `checkCacheValid` and `invalidateCache` to take in an object in addition to a string parameter.  The object would contain the `DEFAULT_KEY` set by the reducer.  Example usage:

```
import { checkCacheValid } from 'redux-cache';

function fetchData(...args) {
    return (dispatch, getState) => {
        const reducer = getState().path.to.combined.reducer;
        if(checkCacheValid(getState, reducer)) { return null; }
        // perform action
    };
}
```

2.  Update `checkCacheValid` and `invalidateCache` to handle nested strings.  It would follow the same usage as (1), except the function call would be `checkCacheValid(getState, "path.to.combined.reducer")`.  Lodash's get function would allow easy implementation of this: https://lodash.com/docs/4.17.5#get

3.  Have the flexibility for both (1) and (2)!

Thoughts?

**Comment by patrickgordon** [comment]
@irtiza-rizvi I guess my concern there would be handling dynamic keys.

An example use case:
https://github.com/patrickgordon/coothaback/blob/master/src/leaderboard/leaderboardActions.js#L35

By having it use the accessStrategy as a function to determine how to access the cache key it lends itself to more composable uses. 

Would you see your proposed approach as allowing the same flexibility?

**Comment by irtiza-rizvi** [comment]
@patrickgordon yeah, both approach (1) and (2) would have the same flexibility.  Imagine if the `checkCacheValid` function was as follows (note: not the cleanest code, can definitely be improved!):

```
export const getCacheUntil = (getState: GetState, reducerAccess, cacheKey: string): number => {
    const state = getState();

    if(typeof reducerAccess === "string") {
        return state && state[reducerAccess] && state[reducerAccess][cacheKey] ? 
            state[reducerAccess][cacheKey] : 0;
    }
    else if(reducerAccess instanceof Array) {
        const reducer = state;
        for(var key in reducerAccess) {
            if(!reducer) {
                return 0;
            }
            reducer = reducer[key];
        }
        return reducer ? reducer[cacheKey] : 0;
    }
    else if(typeof reducerAccess === "object") {
        return reducerAccess && reducerAccess[cacheKey] ? 
            reducerAccess[cacheKey] : 0;
    }

    return 0;
}

export const checkCacheValid = (getState: GetState, reducerAccess, args: Args = {}): boolean => {
	const { 
		cacheKey = DEFAULT_KEY
	} = args;

	const cacheUntil = getCacheUntil(getState, reducerAccess, cacheKey);
	
	const currentTime: number = Date.now();
	
	return !!(cacheUntil > currentTime);
};
```

The `getCacheUntil` function can be used throughout the package.  Given this approach, you can update your `leaderboardActions` as follows:

```
export const fetchClubLeaderboard = (clubId) => (dispatch, getState) => {
	const isCacheValid = checkCacheValid(getState, ["entities", "leaderboard", clubId]);
	if (isCacheValid) { return null; }

	// ...make API call...
};
```

If you feel the `accessStrategy` approach is better, then the discussion prior to the alternative approaches I proposed would most likely work.

**Comment by patrickgordon** [comment]
@irtiza-rizvi thanks for the code samples. Given me a bit to think about. At the minute I'm working on a PR to increase the code coverage of `cacheEnhancer.ts` such that we can be more confident of refactors.

Then I will do a PR for this issue. Alternatively, I'd welcome one from yourself :)

**Comment by patrickgordon** [comment]
I will be working on this very shortly. Sorry for the tremendously large delay :grimacing:

**Comment by irtiza-rizvi** [comment]
@patrickgordon Not a problem!  I have been extremely busy myself :)

**Comment by BaptWaels** [comment]
Hi @patrickgordon , Have you got some time to work on this feature ? Or do you need some help ?

**Comment by patrickgordon** [comment]
Hey @BaptWaels - I do actually have some time. I will try tomorrow to get a PR WIP going

**Comment by patrickgordon** [comment]
@irtiza-rizvi @BaptWaels there's a PR there which just needs a bit more polishing tomorrow/this weekend. Eager to get your thoughts & feedback.

**Comment by Vargentum** [comment]
@patrickgordon I've just digged into your solution proposed in PR, and found it super-flexible. Exactly what I needed. Just one notice: Redux doesn't promote unserializable state, which introduced by including `accessStrategy` and `invalidateStrategy` in action. But this concern looks like too theoretical.

Would you like to merge it and create a new version?

**Comment by patrickgordon** [comment]
Hey @Vargentum can you elaborate on the unserializable state comment? Would like to make sure I understand you before I go ahead and merge & update

**Comment by Vargentum** [comment]
@patrickgordon non-serializable objects, like functions, can break store rehydration and cause problems with time-travelling. More details [here](https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state)

**Comment by tims-j** [comment]
Closing this issue as the library is no longer in active development.
