### ISSUE TITLE
Pass prop instead of static string to axios.get

### ISSUE THREAD

**Issue by bartonwelt** [JumboInteractiveLimited/redux-cache#5]
Hello, I was wondering how you'd modify your example project to pass a prop value to `axios.get()` instead of hard coding it. I was trying to pass it via ownProps in the map functions, but ran into the error `getPosts is not a function`.

Thanks.

**Comment by patrickgordon** [comment]
Change this:
```
const mapDispatchToProps = {
	getPosts: (myProp) => getPosts(myProp),
	invalidateCache: (cacheKeys) => invalidateCache(cacheKeys)
};
```

then update the `getPosts` in `/src/redux/posts.js` to accept a parameter.

**Comment by bartonwelt** [comment]
@patrickgordon That did it. I was trying to pass the prop in `mapDispatchToProps` without first adding it to the function in `componentWillMount`.

**Comment by patrickgordon** [comment]
OK Great. Glad that worked
Cheers
